# Generated by Django 4.2.13 on 2024-06-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(default=None, max_length=100, unique=True)),
                ("password", models.CharField(default=None, max_length=100)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("role", models.CharField(default="admin", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(default=None, max_length=100, unique=True)),
                ("password", models.CharField(default=None, max_length=100)),
                ("roll", models.IntegerField(blank=True, null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("role", models.CharField(default="volunteer", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("roll", models.IntegerField(blank=True, null=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="political_app.volunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "constituency",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("role", models.CharField(default="client", max_length=100)),
                ("email", models.EmailField(default=None, max_length=100, unique=True)),
                ("password", models.CharField(default=None, max_length=100)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="political_app.task",
                    ),
                ),
            ],
        ),
    ]
