# Generated by Django 4.2.13 on 2024-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("political_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="phone_number",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.IntegerField(
                blank=True, default=None, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="phone_number",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
