# Generated by Django 4.2.13 on 2024-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "political_app",
            "0002_alter_admin_phone_number_alter_client_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
