# Generated by Django 4.2.13 on 2024-06-26 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("political_app", "0002_client_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="task_status",
        ),
    ]
