# Generated by Django 4.2.13 on 2024-06-26 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("political_app", "0003_rename_status_task_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_status",
            new_name="status",
        ),
    ]
