# Generated by Django 4.2.13 on 2024-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "political_app",
            "0003_alter_admin_phone_number_alter_client_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
